import { Component } from '@angular/core';
import { Patient } from '../../models/user';

@Component({
    selector: 'app-patients',
    templateUrl: './patients.component.html',
    styleUrl: './patients.component.scss',
})
export class PatientsComponent {
    tableHeaders = [
        'id',
        'firstName',
        'lastName',
        'status',
        'age',
        'gender',
        'appointmentDate',
        'wardId',
    ];
    headerAlias = {
        id: 'Patient ID',
        firstName: 'First name',
        lastName: 'Last name',
        appointmentDate: 'Appointment date',
        wardId: 'Ward ID',
    };
    tableData: Patient[] = [
        {
            id: 1,
            userName: '',
            password: '',
            firstName: 'Anne',
            middleName: '',
            lastName: 'Hathaway',
            age: 34,
            gender: 'Female',
            dateOfBirth: new Date().toDateString(),
            country: 'America',
            state: 'California',
            city: 'San Diego',
            addressLine1: 'addr line 1',
            addressLine2: 'addr line 2',
            landmark: 'landmark',
            pinCode: '657832',
            contact: '1234567890',
            email: 'anne@gmail.com',
            profilePicture: 'path/to/profile',
            emergencyContactName: 'er name',
            emergencyContactNumber: '1234567890',
            role: 'patient',
            purpose: 'regular checkup',
            temperature: '93C',
            bloodPressure: '108Hg',
            admissionDate: new Date().toDateString(),
            dischargeDate: '',
            status: 'active',
            appointmentDate: new Date().toUTCString(),
            wardId: 'W04',
        },
        {
            id: 2,
            userName: '',
            password: '',
            firstName: 'Bob',
            middleName: '',
            lastName: 'Odenkirk',
            age: 45,
            gender: 'Male',
            dateOfBirth: new Date().toDateString(),
            country: 'America',
            state: 'California',
            city: 'San Diego',
            addressLine1: 'addr line 1',
            addressLine2: 'addr line 2',
            landmark: 'landmark',
            pinCode: '657832',
            contact: '1234567890',
            email: 'bob@gmail.com',
            profilePicture: 'path/to/profile',
            emergencyContactName: 'er name',
            emergencyContactNumber: '1234567890',
            role: 'patient',
            purpose: 'regular checkup',
            temperature: '93C',
            bloodPressure: '108Hg',
            admissionDate: new Date().toUTCString(),
            dischargeDate: '',
            status: 'inactive',
            appointmentDate: '',
            wardId: '',
        },
        {
            id: 3,
            userName: '',
            password: '',
            firstName: 'Subhash',
            middleName: '',
            lastName: 'Sen',
            age: 27,
            gender: 'Male',
            dateOfBirth: new Date().toDateString(),
            country: 'India',
            state: 'West Bengal',
            city: 'Kolkata',
            addressLine1: 'addr line 1',
            addressLine2: 'addr line 2',
            landmark: 'landmark',
            pinCode: '657832',
            contact: '1234567890',
            email: 'subhash@gmail.com',
            profilePicture: 'path/to/profile',
            emergencyContactName: 'er name',
            emergencyContactNumber: '1234567890',
            role: 'patient',
            purpose: 'regular checkup',
            temperature: '93C',
            bloodPressure: '108Hg',
            admissionDate: new Date().toUTCString(),
            dischargeDate: '',
            status: 'inactive',
            appointmentDate: '',
            wardId: 'W05',
        },
        {
            id: 4,
            userName: '',
            password: '',
            firstName: 'Rajesh',
            middleName: '',
            lastName: 'Kumar',
            age: 68,
            gender: 'Male',
            dateOfBirth: new Date().toDateString(),
            country: 'India',
            state: 'West Bengal',
            city: 'Kolkata',
            addressLine1: 'addr line 1',
            addressLine2: 'addr line 2',
            landmark: 'landmark',
            pinCode: '657832',
            contact: '1234567890',
            email: 'rajesh@gmail.com',
            profilePicture: 'path/to/profile',
            emergencyContactName: 'er name',
            emergencyContactNumber: '1234567890',
            role: 'patient',
            purpose: 'regular checkup',
            temperature: '93C',
            bloodPressure: '108Hg',
            admissionDate: new Date().toUTCString(),
            dischargeDate: '',
            status: 'active',
            appointmentDate: new Date().toUTCString(),
            wardId: '',
        },
        {
            id: 5,
            userName: '',
            password: '',
            firstName: 'Neha',
            middleName: '',
            lastName: 'Sharma',
            age: 78,
            gender: 'Female',
            dateOfBirth: new Date().toDateString(),
            country: 'India',
            state: 'Maharashtra',
            city: 'Mumbai',
            addressLine1: 'addr line 1',
            addressLine2: 'addr line 2',
            landmark: 'landmark',
            pinCode: '657832',
            contact: '1234567890',
            email: 'neha@gmail.com',
            profilePicture: 'path/to/profile',
            emergencyContactName: 'er name',
            emergencyContactNumber: '1234567890',
            role: 'patient',
            purpose: 'regular checkup',
            temperature: '93C',
            bloodPressure: '108Hg',
            admissionDate: new Date().toUTCString(),
            dischargeDate: '',
            status: 'inactive',
            appointmentDate: '',
            wardId: '',
        },
    ];

    viewPatientDetails(patient: Patient) {
        console.log(patient);
    }

    getFullAddress(patient: Patient) {
        return (
            patient.addressLine1 +
            ', ' +
            patient.addressLine2 +
            ', ' +
            patient.city +
            ', ' +
            patient.state +
            ', ' +
            patient.country
        );
    }
}
